---
title: "Untitled"
author: "Li Yuan"
date: "6/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Check the Private Acquisition deals

```{r}
#pri_acd <- read_csv(file = "/Users/liyuan/Dropbox/George\ RA\ Li\ Yuan\ work/Private\ Acquisition\ Deals\ -\ identification\ of\ missing\ attorneys\ CORRECTED.csv", cols(MI.x = col_character(), Last = col_character())) %>% select(1:12) %>% slice(1:1064)

pri_acd <- read_csv("~/Dropbox/George RA Li Yuan work/Private Acquisition Deals - identification of missing attorneys CORRECTED.csv", 
    col_types = cols(First = col_character(), 
        MI.x = col_character(), Last = col_character()))%>% select(1:12) %>% slice(1:1064)
View(pri_acd)
```

```{r}
sehalf <- pri_acd[647:1079, 1:8]

int <- intersect(sehalf, pri_acd[1:646, 1:8]) 

colnames(int)
int %>%
  inner_join(pri_acd, by = c("deal"="deal", "Signing date"="Signing date", "Closing date"="Closing date", "First"="First", "MI.x" = "MI.x", "Last" = "Last", "Law Firm 1"="Law Firm 1", "Type"="Type")) %>% View
View(int)
write_csv(x = int, file = "intersection_first_second.csv")
```

```{r}
merge_deal_lawyer <- read_csv("merge_deal_lawyer.csv")
View(merge_deal_lawyer)
```

# 

```{r}
sname <- function(x){
  if(grepl(", Jr\\.$|, Sr\\.$", x)){
    x <- substr(x, 1, nchar(x)-5)
    x <- strsplit(x, split = " ")[[1]]
    if(length(x) == 3){ return(x) }
    else if(length(x) == 2) { return(c(x[1], NA, x[2])) }
    else if(length(x) == 1) { return(c(x[1], NA, NA)) }
    else { return(c(paste0(x, collapse = " "), NA, NA)) }
  }
  else if(grepl(", Jr\\.uire$", x)){
    x <- substr(x, 1, nchar(x) - 9)
    x <- strsplit(x, split = " ")[[1]]
    if(length(x) == 3){ return(x) }
    else if(length(x) == 2) { return(c(x[1], NA, x[2])) }
    else if(length(x) == 1) { return(c(x[1], NA, NA)) }
    else { return(c(paste0(x, collapse = " "), NA, NA)) }
  }
  else if(grepl(", Jr\\. P\\.C\\.$", x)){
    x <- substr(x, 1, nchar(x) - 10)
    x <- strsplit(x, split = " ")[[1]]
    if(length(x) == 3){ return(x) }
    else if(length(x) == 2) { return(c(x[1], NA, x[2])) }
    else if(length(x) == 1) { return(c(x[1], NA, NA)) }
    else { return(c(paste0(x, collapse = " "), NA, NA)) }
  }
  else if(grepl(", PC$", x)){
    x <- substr(x, 1, nchar(x) - 4)
    x <- strsplit(x, split = " ")[[1]]
    if(length(x) == 3){ return(x) }
    else if(length(x) == 2) { return(c(x[1], NA, x[2])) }
    else if(length(x) == 1) { return(c(x[1], NA, NA)) }
    else { return(c(paste0(x, collapse = " "), NA, NA)) }
  }
  else if(grepl(". Jr, .|. Jr\\., .", x)){
    y <- strsplit(x, split = " ")[[1]]
    if(grepl(". Jr, .", x)) { y <- y[y != "Jr,"]}
    else { y <- y[y != "Jr.,"]}
    if(length(y) == 3) { return(c(y[2], y[3], y[1])) }
    else if(length(y) == 2) { return(c(y[2], y[1])) }
    else { return(c(paste0(x, collapse = " "), NA, NA)) }
  }
  else if(!grepl(",", x)){
    x <- strsplit(x, split = " ")[[1]]
    if(length(x) == 4){ return(c(x[1], x[2], paste0(x[3], " ", x[4]))) }
    else if(length(x) == 3){ return(x)}
    else if(length(x) == 2) { return(c(x[1], NA, x[2])) }
    else if(length(x) == 1) { return(c(x[1], NA, NA)) }
    else { return(c(paste0(x, collapse = " "), NA, NA)) }
  }
  else if(grepl(",", x)){
    x <- gsub(",", "", x)
    x <- strsplit(x, split = " ")[[1]]
    if(length(x) == 4){ return(c(x[2], paste0(x[3], " ", x[4]), x[1])) }
    else if(length(x) == 3){ return(c(x[2], x[3], x[1])) }
    else if(length(x) == 2) { return(c(x[2], NA, x[1])) }
    else if(length(x) == 1) { return(c(x[1], NA, NA)) }
    else { return(c(paste0(x, collapse = " "), NA, NA)) }
  }
  else if(x == "n/a"){
    return(rep(NA, 3))
  }
  else{ return(c(x, NA, NA)) }
}

a <- sname("Morris Jr, R. Cabell")
a

#strsplit("Glen R. Van Ligten", split = "[:upper:]")
# grepl("[A-Z]\\.", "I.")
# x <- c("hj", "U.", "T.", "gy")
# y <- unlist(lapply(x, FUN = function(x) grepl("[A-Z]\\.", x)))
# x[y]
# x <- "Cohenand, Stephen M. L."
# if(grepl(",", x)){
#     x <- gsub(",", "", x)
#     x <- strsplit(x, split = " ")[[1]]
#     if(length(x) == 3){ return(c(x[2], x[3], x[1])) }
#     else if(length(x) == 2) { print(c(x[2], NA, x[1])) }
#     else if(length(x) == 1) { print(c(x[1], NA, NA)) }
#   }
```

```{r}
new_pri <- NULL
for(i in 1:nrow(pri_acd)){
  this_row <- pri_acd[i, ]
  num_law <- sum(apply(this_row[1, 9:12], MARGIN = 1, FUN = function(x) !is.na(x)))
  if(num_law == 0) { next }
  temp <- this_row[1, 1:8][rep(1, num_law), ]
  
  law <- apply(this_row[1, 9:12], MARGIN = 1, FUN = function(x) x)
  law <- law[!is.na(law)]
  if(num_law == 1 & law[1] == "n/a") { next }
  
  for(j in 1:length(law)){
    sn <- sname(law[j])
    temp[j, "First"] <- sn[1]
    temp[j, "MI.x"] <- sn[2]
    temp[j, "Last"] <- sn[3]
  }
  
  new_pri <- rbind(new_pri, temp)
}
View(new_pri)

write_csv(x = new_pri, file = "private_aci_new.csv")
```

